apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-8arc
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-nbvr-tenant/rhtap-demo-app/hacbs-test-project-8arc@sha256:7cdf4c0d040c3bd9b95b27f4ea7da03361f934ab31d204a1364c2f3121914ef4
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
