apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-8arc
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-8arc
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-8arc
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-8arc
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-8arc
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-nbvr-tenant/rhtap-demo-app/hacbs-test-project-8arc@sha256:3ed0eb5a2370b90bbd73d2c463f4d87516315b32b13dd2171754e26fc3abb5bc
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
